# Generated by Django 4.2.7 on 2024-01-02 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField()),
                ('message', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=200)),
            ],
        ),
    ]
