# Generated by Django 4.2.7 on 2024-01-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date_time',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='email',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='category',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='message',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='phone',
        ),
        migrations.AddField(
            model_name='appointment',
            name='Name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Message',
            field=models.TextField(default='', max_length=500),
        ),
    ]
